apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJ0YXRyb2MiLCJwYXNzd29yZCI6InM0Ymdtd2RGSC0zLTl6N2lwVTVpIiwiZW1haWwiOiJ0YXRyb2NAZ21haWwuY29tIiwiYXV0aCI6ImRHRjBjbTlqT25NMFltZHRkMlJHU0MwekxUbDZOMmx3VlRWcCJ9fX0=
kind: Secret
metadata:
  name: {{ .Values.pull_secret_name }}
  namespace: {{ .Values.namespace }}
type: kubernetes.io/dockerconfigjson